name: linter

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    environment: Testing
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Check if Flux credentials are available
        id: check_flux_credentials
        run: |
          if [ -n "${{ secrets.FLUX_USERNAME }}" ] && [ -n "${{ secrets.FLUX_LICENSE_KEY }}" ]; then
            echo "flux_credentials_available=true" >> $GITHUB_OUTPUT
          else
            echo "flux_credentials_available=false" >> $GITHUB_OUTPUT
          fi

      - name: Add Flux Credentials (if available)
        if: steps.check_flux_credentials.outputs.flux_credentials_available == 'true'
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install Dependencies
        run: |
          # Skip Flux package if credentials are not available
          if [ "${{ steps.check_flux_credentials.outputs.flux_credentials_available }}" = "false" ]; then
            echo "Flux credentials not available, skipping Flux package installation"
            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-req=ext-redis
          else
            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          fi
          npm install

      - name: Run Pint
        run: vendor/bin/pint

      # - name: Commit Changes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: fix code style
      #     commit_options: '--no-verify'
      #     file_pattern: '!.github/workflows/* **/*'
