name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: Testing

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm i

      - name: Check if Flux credentials are available
        id: check_flux_credentials
        run: |
          if [ -n "${{ secrets.FLUX_USERNAME }}" ] && [ -n "${{ secrets.FLUX_LICENSE_KEY }}" ]; then
            echo "flux_credentials_available=true" >> $GITHUB_OUTPUT
          else
            echo "flux_credentials_available=false" >> $GITHUB_OUTPUT
          fi

      - name: Add Flux Credentials (if available)
        if: steps.check_flux_credentials.outputs.flux_credentials_available == 'true'
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install Dependencies
        run: |
          # Skip Flux package if credentials are not available
          if [ "${{ steps.check_flux_credentials.outputs.flux_credentials_available }}" = "false" ]; then
            echo "Flux credentials not available, skipping Flux package installation"
            composer install --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-req=ext-redis
          else
            composer install --no-interaction --prefer-dist --optimize-autoloader
          fi

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Build Assets
        run: npm run build

      - name: Run Tests
        run: ./vendor/bin/pest